### PR TITLE
Database

### PR DESCRIPTION
**Pull request by bobbiec**
This PR uses a SQLite database to persist data. 

I used https://sqlitebrowser.org/ to define the schema based on what we did from Homework 3, and I generated a migration using SQLite Browser's Export -> SQL feature to generate the dronuts.db.sql file.

You'll need to run `npm run init-db` to generate the database on first run. 

The express server exposes 3 database-related endpoints:
- GET `/api/donuts` gives all donuts
- GET `/api/donuts/donutId` gives a single donut (or 404 if no donut with that Id exists)
- POST `/api/donuts` adds a new donut to the db

It's already hooked up to the Menu frontend stuff.

For documentation, see the SQLite3 API: https://github.com/mapbox/node-sqlite3/wiki/API

### CODE REVIEW

**Comment by ykotturi** [comment]
I've pulled this branch and am attempting to run locally. I see this error when running ```npm run init-db```
image

The error seems to be caused by this initialization of the donuts table (Lines 11-13) 
image


Did you run into this error when you originally ran ```npm run init-db``` ?

**Comment by bobbiec** [comment]
Oops, this is because the .db file is checked in. I'll add it to the
gitignore, for now you can just delete the db file and run init again.

**Comment by ykotturi** [comment]
Got it - removed the .db file, installed dependencies, and was able to successfully launch app locally. Looks like the validation is catching somewhere -- when I go to click "Check out" I see this: 

image

**Comment by ykotturi** [comment]
Oh, this proxy error was displayed in the terminal, which might be the cause of the validation error:

image

**Comment by ykotturi** [comment]
re: pair programming w/ Bobbie -- Seems the problem was with the credit API and how group5 was somehow removed. Fixed by submitting PUT request to credit API with id = 5, friendly name = group5. Ready to merge!

**Pull request merged**
